config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students
  authenticated :user do
    root "students#index", as: "authenticated_root"
  end

  root 'welcome#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :find_student, only: [:show, :edit, :update, :destroy ]


  def index
    @students = Student.all
  end

  def show
    @stu = Student.find(params[:id])
  end

  def new
    @stu = Student.new
  end

  def create
    @stu = Student.new(student_params)

    if @stu.save
      redirect_to @stu
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @stu.update(student_params)
      redirect_to @stu
    else
      render 'edit'
    end
  end

  def destroy
    @stu.destroy
    redirect_to students_path
  end

  private

    def find_student
        @stu = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name,:course1,:course2,:course3)
    end




end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Student Management Information
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags
  = csp_meta_tag
%body
  %header
    .header_inner
      = link_to "SMS",root_path,id: "logo"

      %nav
        - if user_signed_in?
          = link_to "Create New Entry",new_student_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete

        - else
          = link_to "Log In", new_user_session_path

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/students/_form.html.haml
= simple_form_for @stu do |f|
  = f.input :name
  = f.input :course1
  = f.input :course2
  = f.input :course3
  = f.button :submit,class: "button"

app/views/students/edit.html.haml
.wrapper_with_padding
  %h1 Fix the Student Record

  = render 'form'
  = link_to "Cancel", student_path

app/views/students/index.html.haml
.wrapper_with_padding
  #students.clearfix
    - unless @students.blank?
      - @students.each do |doc|
        %a{href: (url_for [doc])}
          .doc
            %p.name= doc.name
    - else
      %h2 Create Student
      %button= link_to "Create Student", new_student_path

app/views/students/new.html.haml
.wrapper_with_padding
  %h1 Add New Student

  = render 'form'

app/views/students/show.html.haml
.wrapper_with_padding
  %h1= @stu.name
  %p= @stu.course1
  %p= @stu.course2
  %p= @stu.course3

  .buttons
    = link_to "All Students", students_path, class: "button"
    = link_to "Fix Doc", edit_student_path(@stu), class: "button"
    = link_to "Trash It",  student_path(@stu), method: :delete, data: {confirm: "Are you sure?"},class: "button"

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Student Management System
    %button= link_to "Enter", new_user_registration_path

#callouts
  .callout_inner
  .wrapper
  .callout
    %h2 Organize
    